export const speakerList = [
  {
    label: '冷酷哥哥（多情感）',
    value: 'zh_male_lengkugege_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['生气', '冷漠', '恐惧', '开心', '厌恶', '中性', '悲伤', '沮丧'],
    business: [],
    mix: false,
  },
  {
    label: '甜心小美（多情感）',
    value: 'zh_female_tianxinxiaomei_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['悲伤', '恐惧', '厌恶', '中性'],
    business: ['剪映'],
    mix: false,
  },
  {
    label: '高冷御姐（多情感）',
    value: 'zh_female_gaolengyujie_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: [
      '开心',
      '悲伤',
      '生气',
      '惊讶',
      '恐惧',
      '厌恶',
      '激动',
      '冷漠',
      '中性',
    ],
    business: ['剪映'],
    mix: false,
  },
  {
    label: '傲娇霸总（多情感）',
    value: 'zh_male_aojiaobazong_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['中性', '开心', '愤怒', '厌恶'],
    business: ['剪映'],
    mix: false,
  },
  {
    label: '广州德哥（多情感）',
    value: 'zh_male_guangzhoudege_emo_mars_bigtts',
    languages: ['中文'],
    emotions: ['生气', '恐惧', '中性'],
    business: ['剪映'],
    mix: true,
  },
  {
    label: '京腔侃爷（多情感）',
    value: 'zh_male_jingqiangkanye_emo_mars_bigtts',
    languages: ['中文'],
    emotions: ['开心', '生气', '惊讶', '厌恶', '中性'],
    business: ['剪映'],
    mix: true,
  },
  {
    label: '邻居阿姨（多情感）',
    value: 'zh_female_linjuayi_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['中性', '愤怒', '冷漠', '沮丧', '惊讶'],
    business: ['剪映'],
    mix: false,
  },
  {
    label: '优柔公子（多情感）',
    value: 'zh_male_yourougongzi_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['开心', '生气', '恐惧', '厌恶', '激动', '中性', '沮丧'],
    business: ['剪映'],
    mix: false,
  },
  {
    label: '儒雅男友（多情感）',
    value: 'zh_male_ruyayichen_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['开心', '悲伤', '生气', '恐惧', '激动', '冷漠', '中性'],
    business: ['剪映'],
    mix: false,
  },
  {
    label: '俊朗男友（多情感）',
    value: 'zh_male_junlangnanyou_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['开心', '悲伤', '生气', '惊讶', '恐惧', '中性'],
    business: ['剪映'],
    mix: false,
  },
  {
    label: '北京小爷（多情感）',
    value: 'zh_male_beijingxiaoye_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['生气', '惊讶', '恐惧', '激动', '冷漠', '中性'],
    business: [],
    mix: false,
  },
  {
    label: '柔美女友（多情感）',
    value: 'zh_female_roumeinvyou_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: [
      '开心',
      '悲伤',
      '生气',
      '惊讶',
      '恐惧',
      '厌恶',
      '激动',
      '冷漠',
      '中性',
    ],
    business: [],
    mix: false,
  },
  {
    label: '阳光青年（多情感）',
    value: 'zh_male_yangguangqingnian_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['开心', '悲伤', '生气', '恐惧', '激动', '冷漠', '中性'],
    business: [],
    mix: false,
  },
  {
    label: '魅力女友（多情感）',
    value: 'zh_female_meilinvyou_emo_v2_mars_bigtts',
    languages: ['中文'],
    emotions: ['悲伤', '恐惧', '中性'],
    business: [],
    mix: false,
  },
  {
    label: '爽快思思（多情感）',
    value: 'zh_female_shuangkuaisisi_emo_v2_mars_bigtts',
    languages: ['中文', '英式英语'],
    emotions: ['开心', '悲伤', '生气', '惊讶', '激动', '冷漠', '中性'],
    business: [],
    mix: false,
  },
  {
    label: 'Candice',
    value: 'en_female_candice_emo_v2_mars_bigtts',
    languages: ['美式英语'],
    emotions: [
      '深情',
      '愤怒',
      'ASMR',
      '对话',
      '闲聊',
      '兴奋',
      '愉悦',
      '中性',
      '温暖',
    ],
    business: [],
    mix: false,
  },
  {
    label: 'Serena',
    value: 'en_female_skye_emo_v2_mars_bigtts',
    languages: ['美式英语'],
    emotions: [
      '深情',
      '愤怒',
      'ASMR',
      '对话',
      '闲聊',
      '兴奋',
      '愉悦',
      '中性',
      '悲伤',
      '温暖',
    ],
    business: [],
    mix: false,
  },
  {
    label: 'Glen',
    value: 'en_male_glen_emo_v2_mars_bigtts',
    languages: ['美式英语'],
    emotions: [
      '深情',
      '愤怒',
      'ASMR',
      '对话',
      '闲聊',
      '深情',
      '兴奋',
      '愉悦',
      '中性',
      '悲伤',
      '温暖',
    ],
    business: [],
    mix: false,
  },
  {
    label: 'Sylus',
    value: 'en_male_sylus_emo_v2_mars_bigtts',
    languages: ['美式英语'],
    emotions: [
      '深情',
      '愤怒',
      'ASMR',
      '权威',
      '对话',
      '闲聊',
      '兴奋',
      '愉悦',
      '中性',
      '悲伤',
      '温暖',
    ],
    business: [],
    mix: false,
  },
  {
    label: 'Corey',
    value: 'en_male_corey_emo_v2_mars_bigtts',
    languages: ['英式英语'],
    emotions: [
      '愤怒',
      'ASMR',
      '权威',
      '对话',
      '闲聊',
      '深情',
      '兴奋',
      '愉悦',
      '中性',
      '悲伤',
      '温暖',
    ],
    business: [],
    mix: false,
  },
  {
    label: 'Nadia',
    value: 'en_female_nadia_tips_emo_v2_mars_bigtts',
    languages: ['英式英语'],
    emotions: [
      '深情',
      '愤怒',
      'ASMR',
      '对话',
      '闲聊',
      '深情',
      '兴奋',
      '愉悦',
      '中性',
      '悲伤',
      '温暖',
    ],
    business: [],
    mix: false,
  },
  {
    label: 'Tina老师',
    value: 'zh_female_yingyujiaoyu_mars_bigtts',
    languages: ['中文', '英式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '温柔女神',
    value: 'ICL_zh_female_wenrounvshen_239eff5e8ffa_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: 'Vivi',
    value: 'zh_female_vv_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '亲切女声',
    value: 'zh_female_qinqienvsheng_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '机灵小伙',
    value: 'ICL_zh_male_shenmi_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '元气甜妹',
    value: 'ICL_zh_female_wuxi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '知心姐姐',
    value: 'ICL_zh_female_wenyinvsheng_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '阳光阿辰',
    value: 'zh_male_qingyiyuxuan_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '快乐小东',
    value: 'zh_male_xudong_conversation_wvae_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', 'Cici', 'web demo'],
    mix: true,
  },
  {
    label: '冷酷哥哥',
    value: 'ICL_zh_male_lengkugege_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '纯澈女生',
    value: 'ICL_zh_female_feicui_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '初恋女友',
    value: 'ICL_zh_female_yuxin_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '贴心闺蜜',
    value: 'ICL_zh_female_xnx_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '温柔白月光',
    value: 'ICL_zh_female_yry_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '开朗学长',
    value: 'en_male_jason_conversation_wvae_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '魅力苏菲',
    value: 'zh_female_sophie_conversation_wvae_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '贴心妹妹',
    value: 'ICL_zh_female_yilin_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '甜美桃子',
    value: 'zh_female_tianmeitaozi_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '清新女声',
    value: 'zh_female_qingxinnvsheng_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '知性女声',
    value: 'zh_female_zhixingnvsheng_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '清爽男大',
    value: 'zh_male_qingshuangnanda_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '邻家女孩',
    value: 'zh_female_linjianvhai_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', 'Cici'],
    mix: true,
  },
  {
    label: '渊博小叔',
    value: 'zh_male_yuanboxiaoshu_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', 'Cici', '剪映'],
    mix: true,
  },
  {
    label: '阳光青年',
    value: 'zh_male_yangguangqingnian_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', 'Cici', 'StoryAi'],
    mix: true,
  },
  {
    label: '甜美小源',
    value: 'zh_female_tianmeixiaoyuan_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '清澈梓梓',
    value: 'zh_female_qingchezizi_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '解说小明',
    value: 'zh_male_jieshuoxiaoming_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '开朗姐姐',
    value: 'zh_female_kailangjiejie_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '邻家男孩',
    value: 'zh_male_linjiananhai_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '甜美悦悦',
    value: 'zh_female_tianmeiyueyue_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '心灵鸡汤',
    value: 'zh_female_xinlingjitang_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '知性温婉',
    value: 'ICL_zh_female_zhixingwenwan_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '暖心体贴',
    value: 'ICL_zh_male_nuanxintitie_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '开朗轻快',
    value: 'ICL_zh_male_kailangqingkuai_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '活泼爽朗',
    value: 'ICL_zh_male_huoposhuanglang_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '率真小伙',
    value: 'ICL_zh_male_shuaizhenxiaohuo_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '温柔小哥',
    value: 'zh_male_wenrouxiaoge_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '灿灿/Shiny',
    value: 'zh_female_cancan_mars_bigtts',
    languages: ['中文', '美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '爽快思思/Skye',
    value: 'zh_female_shuangkuaisisi_moon_bigtts',
    languages: ['中文', '美式英语'],
    emotions: [],
    business: ['豆包', 'Cici', 'web demo'],
    mix: true,
  },
  {
    label: '温暖阿虎/Alvin',
    value: 'zh_male_wennuanahu_moon_bigtts',
    languages: ['中文', '美式英语'],
    emotions: [],
    business: ['豆包', 'Cici'],
    mix: true,
  },
  {
    label: '少年梓辛/Brayan',
    value: 'zh_male_shaonianzixin_moon_bigtts',
    languages: ['中文', '美式英语'],
    emotions: [],
    business: ['豆包', 'Cici', '剪映'],
    mix: true,
  },
  {
    label: '温柔文雅',
    value: 'ICL_zh_female_wenrouwenya_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '沪普男',
    value: 'zh_male_hupunan_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '粤语小溏',
    value: 'zh_female_yueyunv_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '鲁班七号',
    value: 'zh_male_lubanqihao_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['抖音', '剪映', '豆包'],
    mix: true,
  },
  {
    label: '林潇',
    value: 'zh_female_yangmi_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '抖音', '豆包'],
    mix: true,
  },
  {
    label: '玲玲姐姐',
    value: 'zh_female_linzhiling_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '抖音', '豆包'],
    mix: true,
  },
  {
    label: '春日部姐姐',
    value: 'zh_female_jiyejizi2_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['抖音', '剪映', '豆包'],
    mix: true,
  },
  {
    label: '唐僧',
    value: 'zh_male_tangseng_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['抖音', '豆包'],
    mix: true,
  },
  {
    label: '庄周',
    value: 'zh_male_zhuangzhou_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '抖音'],
    mix: true,
  },
  {
    label: '猪八戒',
    value: 'zh_male_zhubajie_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映订阅', '火山TOB-TTS', '豆包'],
    mix: true,
  },
  {
    label: '感冒电音姐姐',
    value: 'zh_female_ganmaodianyin_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '抖音'],
    mix: true,
  },
  {
    label: '直率英子',
    value: 'zh_female_naying_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '抖音', '豆包'],
    mix: true,
  },
  {
    label: '女雷神',
    value: 'zh_female_leidian_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '豆包'],
    mix: true,
  },
  {
    label: '豫州子轩',
    value: 'zh_male_yuzhouzixuan_moon_bigtts',
    languages: ['中文-河南口音'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '呆萌川妹',
    value: 'zh_female_daimengchuanmei_moon_bigtts',
    languages: ['中文-四川口音'],
    emotions: [],
    business: ['豆包', 'Cici'],
    mix: true,
  },
  {
    label: '广西远舟',
    value: 'zh_male_guangxiyuanzhou_moon_bigtts',
    languages: ['中文-广西口音'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '双节棍小哥',
    value: 'zh_male_zhoujielun_emo_v2_mars_bigtts',
    languages: ['中文-台湾口音'],
    emotions: [],
    business: ['抖音', '剪映', '豆包'],
    mix: false,
  },
  {
    label: '湾湾小何',
    value: 'zh_female_wanwanxiaohe_moon_bigtts',
    languages: ['中文-台湾口音'],
    emotions: [],
    business: ['豆包', 'Cici'],
    mix: true,
  },
  {
    label: '湾区大叔',
    value: 'zh_female_wanqudashu_moon_bigtts',
    languages: ['中文-广东口音'],
    emotions: [],
    business: ['豆包', 'Cici'],
    mix: true,
  },
  {
    label: '广州德哥',
    value: 'zh_male_guozhoudege_moon_bigtts',
    languages: ['中文-广东口音'],
    emotions: [],
    business: ['豆包', 'Cici'],
    mix: true,
  },
  {
    label: '浩宇小哥',
    value: 'zh_male_haoyuxiaoge_moon_bigtts',
    languages: ['中文-青岛口音'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '北京小爷',
    value: 'zh_male_beijingxiaoye_moon_bigtts',
    languages: ['中文-北京口音'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '京腔侃爷/Harmony',
    value: 'zh_male_jingqiangkanye_moon_bigtts',
    languages: ['中文-北京口音', '美式英语'],
    emotions: [],
    business: ['豆包', 'Cici', 'web demo'],
    mix: true,
  },
  {
    label: '妹坨洁儿',
    value: 'zh_female_meituojieer_moon_bigtts',
    languages: ['中文-长沙口音'],
    emotions: [],
    business: ['豆包', '剪映'],
    mix: true,
  },
  {
    label: '纯真少女',
    value: 'ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '奶气小生',
    value: 'ICL_zh_male_xiaonaigou_edf58cf28b8b_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '精灵向导',
    value: 'ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '闷油瓶小哥',
    value: 'ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '黯刃秦主',
    value: 'ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '霸道总裁',
    value: 'ICL_zh_male_badaozongcai_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '妩媚可人',
    value: 'ICL_zh_female_ganli_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '邪魅御姐',
    value: 'ICL_zh_female_xiangliangya_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '嚣张小哥',
    value: 'ICL_zh_male_ms_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '油腻大叔',
    value: 'ICL_zh_male_you_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '孤傲公子',
    value: 'ICL_zh_male_guaogongzi_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '胡子叔叔',
    value: 'ICL_zh_male_huzi_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '性感魅惑',
    value: 'ICL_zh_female_luoqing_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '病弱公子',
    value: 'ICL_zh_male_bingruogongzi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '邪魅女王',
    value: 'ICL_zh_female_bingjiao3_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '傲慢青年',
    value: 'ICL_zh_male_aomanqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '醋精男生',
    value: 'ICL_zh_male_cujingnansheng_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '爽朗少年',
    value: 'ICL_zh_male_shuanglangshaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '撒娇男友',
    value: 'ICL_zh_male_sajiaonanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '温柔男友',
    value: 'ICL_zh_male_wenrounanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '温顺少年',
    value: 'ICL_zh_male_wenshunshaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '粘人男友',
    value: 'ICL_zh_male_naigounanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '撒娇男生',
    value: 'ICL_zh_male_sajiaonansheng_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '活泼男友',
    value: 'ICL_zh_male_huoponanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '甜系男友',
    value: 'ICL_zh_male_tianxinanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '活力青年',
    value: 'ICL_zh_male_huoliqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '开朗青年',
    value: 'ICL_zh_male_kailangqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '冷漠兄长',
    value: 'ICL_zh_male_lengmoxiongzhang_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '天才同桌',
    value: 'ICL_zh_male_tiancaitongzhuo_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '翩翩公子',
    value: 'ICL_zh_male_pianpiangongzi_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '懵懂青年',
    value: 'ICL_zh_male_mengdongqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '冷脸兄长',
    value: 'ICL_zh_male_lenglianxiongzhang_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '病娇少年',
    value: 'ICL_zh_male_bingjiaoshaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '病娇男友',
    value: 'ICL_zh_male_bingjiaonanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '病弱少年',
    value: 'ICL_zh_male_bingruoshaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '意气少年',
    value: 'ICL_zh_male_yiqishaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '干净少年',
    value: 'ICL_zh_male_ganjingshaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '冷漠男友',
    value: 'ICL_zh_male_lengmonanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '精英青年',
    value: 'ICL_zh_male_jingyingqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '热血少年',
    value: 'ICL_zh_male_rexueshaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '清爽少年',
    value: 'ICL_zh_male_qingshuangshaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '中二青年',
    value: 'ICL_zh_male_zhongerqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '凌云青年',
    value: 'ICL_zh_male_lingyunqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '自负青年',
    value: 'ICL_zh_male_zifuqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '不羁青年',
    value: 'ICL_zh_male_bujiqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '儒雅君子',
    value: 'ICL_zh_male_ruyajunzi_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '低音沉郁',
    value: 'ICL_zh_male_diyinchenyu_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '冷脸学霸',
    value: 'ICL_zh_male_lenglianxueba_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '儒雅总裁',
    value: 'ICL_zh_male_ruyazongcai_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '深沉总裁',
    value: 'ICL_zh_male_shenchenzongcai_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '小侯爷',
    value: 'ICL_zh_male_xiaohouye_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '孤高公子',
    value: 'ICL_zh_male_gugaogongzi_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '仗剑君子',
    value: 'ICL_zh_male_zhangjianjunzi_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '温润学者',
    value: 'ICL_zh_male_wenrunxuezhe_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '亲切青年',
    value: 'ICL_zh_male_qinqieqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '温柔学长',
    value: 'ICL_zh_male_wenrouxuezhang_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '高冷总裁',
    value: 'ICL_zh_male_gaolengzongcai_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '冷峻高智',
    value: 'ICL_zh_male_lengjungaozhi_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '孱弱少爷',
    value: 'ICL_zh_male_chanruoshaoye_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '自信青年',
    value: 'ICL_zh_male_zixinqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '青涩青年',
    value: 'ICL_zh_male_qingseqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '学霸同桌',
    value: 'ICL_zh_male_xuebatongzhuo_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '冷傲总裁',
    value: 'ICL_zh_male_lengaozongcai_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '元气少年',
    value: 'ICL_zh_male_yuanqishaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '洒脱青年',
    value: 'ICL_zh_male_satuoqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '直率青年',
    value: 'ICL_zh_male_zhishuaiqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '斯文青年',
    value: 'ICL_zh_male_siwenqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '俊逸公子',
    value: 'ICL_zh_male_junyigongzi_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '仗剑侠客',
    value: 'ICL_zh_male_zhangjianxiake_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '机甲智能',
    value: 'ICL_zh_male_jijiaozhineng_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '奶气萌娃',
    value: 'zh_male_naiqimengwa_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '豆包'],
    mix: true,
  },
  {
    label: '婆婆',
    value: 'zh_female_popo_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映C端', '抖音', '豆包'],
    mix: true,
  },
  {
    label: '高冷御姐',
    value: 'zh_female_gaolengyujie_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', 'Cici'],
    mix: true,
  },
  {
    label: '傲娇霸总',
    value: 'zh_male_aojiaobazong_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '魅力女友',
    value: 'zh_female_meilinvyou_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '剪映'],
    mix: true,
  },
  {
    label: '深夜播客',
    value: 'zh_male_shenyeboke_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '柔美女友',
    value: 'zh_female_sajiaonvyou_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '剪映'],
    mix: true,
  },
  {
    label: '撒娇学妹',
    value: 'zh_female_yuanqinvyou_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '剪映'],
    mix: true,
  },
  {
    label: '病弱少女',
    value: 'ICL_zh_female_bingruoshaonv_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '活泼女孩',
    value: 'ICL_zh_female_huoponvhai_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '东方浩然',
    value: 'zh_male_dongfanghaoran_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '绿茶小哥',
    value: 'ICL_zh_male_lvchaxiaoge_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi', '猫箱'],
    mix: true,
  },
  {
    label: '娇弱萝莉',
    value: 'ICL_zh_female_jiaoruoluoli_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '冷淡疏离',
    value: 'ICL_zh_male_lengdanshuli_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '憨厚敦实',
    value: 'ICL_zh_male_hanhoudunshi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '活泼刁蛮',
    value: 'ICL_zh_female_huopodiaoman_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '固执病娇',
    value: 'ICL_zh_male_guzhibingjiao_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '撒娇粘人',
    value: 'ICL_zh_male_sajiaonianren_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '傲慢娇声',
    value: 'ICL_zh_female_aomanjiaosheng_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '潇洒随性',
    value: 'ICL_zh_male_xiaosasuixing_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '诡异神秘',
    value: 'ICL_zh_male_guiyishenmi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '儒雅才俊',
    value: 'ICL_zh_male_ruyacaijun_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '正直青年',
    value: 'ICL_zh_male_zhengzhiqingnian_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi', '猫箱'],
    mix: true,
  },
  {
    label: '娇憨女王',
    value: 'ICL_zh_female_jiaohannvwang_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi', '猫箱'],
    mix: true,
  },
  {
    label: '病娇萌妹',
    value: 'ICL_zh_female_bingjiaomengmei_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '青涩小生',
    value: 'ICL_zh_male_qingsenaigou_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '纯真学弟',
    value: 'ICL_zh_male_chunzhenxuedi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '优柔帮主',
    value: 'ICL_zh_male_youroubangzhu_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '优柔公子',
    value: 'ICL_zh_male_yourougongzi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '调皮公主',
    value: 'ICL_zh_female_tiaopigongzhu_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '贴心男友',
    value: 'ICL_zh_male_tiexinnanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '少年将军',
    value: 'ICL_zh_male_shaonianjiangjun_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '病娇哥哥',
    value: 'ICL_zh_male_bingjiaogege_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '学霸男同桌',
    value: 'ICL_zh_male_xuebanantongzhuo_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '幽默叔叔',
    value: 'ICL_zh_male_youmoshushu_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '假小子',
    value: 'ICL_zh_female_jiaxiaozi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '温柔男同桌',
    value: 'ICL_zh_male_wenrounantongzhuo_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '幽默大爷',
    value: 'ICL_zh_male_youmodaye_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '枕边低语',
    value: 'ICL_zh_male_asmryexiu_tob',
    languages: ['中文'],
    emotions: [],
    business: ['抖音'],
    mix: true,
  },
  {
    label: '神秘法师',
    value: 'ICL_zh_male_shenmifashi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '娇喘女声',
    value: 'zh_female_jiaochuan_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '抖音'],
    mix: true,
  },
  {
    label: '开朗弟弟',
    value: 'zh_male_livelybro_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '抖音'],
    mix: true,
  },
  {
    label: '谄媚女声',
    value: 'zh_female_flattery_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映', '抖音'],
    mix: true,
  },
  {
    label: '冷峻上司',
    value: 'ICL_zh_male_lengjunshangsi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '醋精男友',
    value: 'ICL_zh_male_cujingnanyou_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '风发少年',
    value: 'ICL_zh_male_fengfashaonian_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '磁性男嗓',
    value: 'ICL_zh_male_cixingnansang_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '成熟总裁',
    value: 'ICL_zh_male_chengshuzongcai_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '傲娇精英',
    value: 'ICL_zh_male_aojiaojingying_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '傲娇公子',
    value: 'ICL_zh_male_aojiaogongzi_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '霸道少爷',
    value: 'ICL_zh_male_badaoshaoye_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '腹黑公子',
    value: 'ICL_zh_male_fuheigongzi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi', '猫箱'],
    mix: true,
  },
  {
    label: '暖心学姐',
    value: 'ICL_zh_female_nuanxinxuejie_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '可爱女生',
    value: 'ICL_zh_female_keainvsheng_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '成熟姐姐',
    value: 'ICL_zh_female_chengshujiejie_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '病娇姐姐',
    value: 'ICL_zh_female_bingjiaojiejie_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '妩媚御姐',
    value: 'ICL_zh_female_wumeiyujie_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', 'StoryAi'],
    mix: true,
  },
  {
    label: '傲娇女友',
    value: 'ICL_zh_female_aojiaonvyou_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '贴心女友',
    value: 'ICL_zh_female_tiexinnvyou_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '性感御姐',
    value: 'ICL_zh_female_xingganyujie_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '病娇弟弟',
    value: 'ICL_zh_male_bingjiaodidi_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '傲慢少爷',
    value: 'ICL_zh_male_aomanshaoye_tob',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', '猫箱'],
    mix: true,
  },
  {
    label: '傲气凌人',
    value: 'ICL_zh_male_aiqilingren_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: '病娇白莲',
    value: 'ICL_zh_male_bingjiaobailian_tob',
    languages: ['中文'],
    emotions: [],
    business: ['猫箱'],
    mix: true,
  },
  {
    label: 'Lauren',
    value: 'en_female_lauren_moon_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Energetic Male II',
    value: 'en_male_campaign_jamal_moon_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Gotham Hero',
    value: 'en_male_chris_moon_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Flirty Female',
    value: 'en_female_product_darcie_moon_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Peaceful Female',
    value: 'en_female_emotional_moon_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Nara',
    value: 'en_female_nara_moon_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Bruce',
    value: 'en_male_bruce_moon_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Michael',
    value: 'en_male_michael_moon_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Cartoon Chef',
    value: 'ICL_en_male_cc_sha_v1_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Lucas',
    value: 'zh_male_M100_conversation_wvae_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: ['豆包', 'Cici', 'web demo'],
    mix: true,
  },
  {
    label: 'Sophie',
    value: 'zh_female_sophie_conversation_wvae_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Daisy',
    value: 'en_female_dacey_conversation_wvae_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: ['豆包', 'Cici', 'web demo'],
    mix: true,
  },
  {
    label: 'Owen',
    value: 'en_male_charlie_conversation_wvae_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: ['豆包', 'Cici'],
    mix: true,
  },
  {
    label: 'Luna',
    value: 'en_female_sarah_new_conversation_wvae_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: ['豆包', 'Cici', 'web demo'],
    mix: true,
  },
  {
    label: 'Michael',
    value: 'ICL_en_male_michael_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: 'Charlie',
    value: 'ICL_en_female_cc_cm_v1_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Big Boogie',
    value: 'ICL_en_male_oogie2_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['TT', '豆包'],
    mix: true,
  },
  {
    label: 'Frosty Man',
    value: 'ICL_en_male_frosty1_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['TT', '豆包'],
    mix: true,
  },
  {
    label: 'The Grinch',
    value: 'ICL_en_male_grinch2_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['TT', '豆包'],
    mix: true,
  },
  {
    label: 'Zayne',
    value: 'ICL_en_male_zayne_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Jigsaw',
    value: 'ICL_en_male_cc_jigsaw_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Chucky',
    value: 'ICL_en_male_cc_chucky_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Clown Man',
    value: 'ICL_en_male_cc_penny_v1_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Kevin McCallister',
    value: 'ICL_en_male_kevin2_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: 'Xavier',
    value: 'ICL_en_male_xavier1_v1_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Noah',
    value: 'ICL_en_male_cc_dracula_v1_tob',
    languages: ['美式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Adam',
    value: 'en_male_adam_mars_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Amanda',
    value: 'en_female_amanda_mars_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Jackson',
    value: 'en_male_jackson_mars_bigtts',
    languages: ['美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Delicate Girl',
    value: 'en_female_daisy_moon_bigtts',
    languages: ['英式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Dave',
    value: 'en_male_dave_moon_bigtts',
    languages: ['英式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Hades',
    value: 'en_male_hades_moon_bigtts',
    languages: ['英式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Onez',
    value: 'en_female_onez_moon_bigtts',
    languages: ['英式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Emily',
    value: 'en_female_emily_mars_bigtts',
    languages: ['英式英语'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: 'Daniel',
    value: 'zh_male_xudong_conversation_wvae_bigtts',
    languages: ['英式英语'],
    emotions: [],
    business: ['豆包', 'Cici', 'web demo'],
    mix: true,
  },
  {
    label: 'Alastor',
    value: 'ICL_en_male_cc_alastor_tob',
    languages: ['英式英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Smith',
    value: 'en_male_smith_mars_bigtts',
    languages: ['英式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Anna',
    value: 'en_female_anna_mars_bigtts',
    languages: ['英式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Ethan',
    value: 'ICL_en_male_aussie_v1_tob',
    languages: ['澳洲英语'],
    emotions: [],
    business: ['CC'],
    mix: true,
  },
  {
    label: 'Sarah',
    value: 'en_female_sarah_mars_bigtts',
    languages: ['澳洲英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Dryw',
    value: 'en_male_dryw_mars_bigtts',
    languages: ['澳洲英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'Diana',
    value: 'multi_female_maomao_conversation_wvae_bigtts',
    languages: ['西语'],
    emotions: [],
    business: ['Cici'],
    mix: false,
  },
  {
    label: 'Lucía',
    value: 'multi_male_M100_conversation_wvae_bigtts',
    languages: ['西语'],
    emotions: [],
    business: ['Cici'],
    mix: false,
  },
  {
    label: 'Sofía',
    value: 'multi_female_sophie_conversation_wvae_bigtts',
    languages: ['西语'],
    emotions: [],
    business: [],
    mix: false,
  },
  {
    label: 'Daníel',
    value: 'multi_male_xudong_conversation_wvae_bigtts',
    languages: ['西语'],
    emotions: [],
    business: [],
    mix: false,
  },
  {
    label: 'ひかる（光）',
    value: 'multi_zh_male_youyoujunzi_moon_bigtts',
    languages: ['日语'],
    emotions: [],
    business: ['Cici'],
    mix: false,
  },
  {
    label: 'さとみ（智美）',
    value: 'multi_female_sophie_conversation_wvae_bigtts',
    languages: ['日语'],
    emotions: [],
    business: [],
    mix: false,
  },
  {
    label: 'まさお（正男）',
    value: 'multi_male_xudong_conversation_wvae_bigtts',
    languages: ['日语'],
    emotions: [],
    business: [],
    mix: false,
  },
  {
    label: 'つき（月）',
    value: 'multi_female_maomao_conversation_wvae_bigtts',
    languages: ['日语'],
    emotions: [],
    business: ['Cici'],
    mix: false,
  },
  {
    label: 'あけみ（朱美）',
    value: 'multi_female_gaolengyujie_moon_bigtts',
    languages: ['日语'],
    emotions: [],
    business: ['Cici'],
    mix: false,
  },
  {
    label: 'かずね（和音）/Javier or Álvaro',
    value: 'multi_male_jingqiangkanye_moon_bigtts',
    languages: ['日语', '西语'],
    emotions: [],
    business: ['Cici'],
    mix: false,
  },
  {
    label: 'はるこ（晴子）/Esmeralda',
    value: 'multi_female_shuangkuaisisi_moon_bigtts',
    languages: ['日语', '西语'],
    emotions: [],
    business: ['Cici'],
    mix: false,
  },
  {
    label: 'ひろし（広志）/Roberto',
    value: 'multi_male_wanqudashu_moon_bigtts',
    languages: ['日语', '西语'],
    emotions: [],
    business: ['Cici'],
    mix: false,
  },
  {
    label: '理性圆子',
    value: 'ICL_zh_female_lixingyuanzi_cs',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '清甜桃桃',
    value: 'ICL_zh_female_qingtiantaotao_cs',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '清晰小雪',
    value: 'ICL_zh_female_qingxixiaoxue_cs',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '清甜莓莓',
    value: 'ICL_zh_female_qingtianmeimei_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '开朗婷婷',
    value: 'ICL_zh_female_kailangtingting_cs',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '清新沐沐',
    value: 'ICL_zh_male_qingxinmumu_cs',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '爽朗小阳',
    value: 'ICL_zh_male_shuanglangxiaoyang_cs',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '清新波波',
    value: 'ICL_zh_male_qingxinbobo_cs',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '温婉珊珊',
    value: 'ICL_zh_female_wenwanshanshan_cs',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '甜美小雨',
    value: 'ICL_zh_female_tianmeixiaoyu_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '热情艾娜',
    value: 'ICL_zh_female_reqingaina_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '甜美小橘',
    value: 'ICL_zh_female_tianmeixiaoju_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '沉稳明仔',
    value: 'ICL_zh_male_chenwenmingzai_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '亲切小卓',
    value: 'ICL_zh_male_qinqiexiaozhuo_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '灵动欣欣',
    value: 'ICL_zh_female_lingdongxinxin_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '乖巧可儿',
    value: 'ICL_zh_female_guaiqiaokeer_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '暖心茜茜',
    value: 'ICL_zh_female_nuanxinqianqian_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '软萌团子',
    value: 'ICL_zh_female_ruanmengtuanzi_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '阳光洋洋',
    value: 'ICL_zh_male_yangguangyangyang_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '软萌糖糖',
    value: 'ICL_zh_female_ruanmengtangtang_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '秀丽倩倩',
    value: 'ICL_zh_female_xiuliqianqian_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '开心小鸿',
    value: 'ICL_zh_female_kaixinxiaohong_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '轻盈朵朵',
    value: 'ICL_zh_female_qingyingduoduo_cs_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '暖阳女声',
    value: 'zh_female_kefunvsheng_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '悠悠君子',
    value: 'zh_male_M100_conversation_wvae_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', 'Cici', 'web demo'],
    mix: true,
  },
  {
    label: '文静毛毛',
    value: 'zh_female_maomao_conversation_wvae_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包', 'web demo'],
    mix: true,
  },
  {
    label: '倾心少女',
    value: 'ICL_zh_female_qiuling_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '醇厚低音',
    value: 'ICL_zh_male_buyan_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '咆哮小哥',
    value: 'ICL_zh_male_BV144_paoxiaoge_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '和蔼奶奶',
    value: 'ICL_zh_female_heainainai_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '邻居阿姨',
    value: 'ICL_zh_female_linjuayi_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '温柔小雅',
    value: 'zh_female_wenrouxiaoya_moon_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['豆包'],
    mix: true,
  },
  {
    label: '天才童声',
    value: 'zh_male_tiancaitongsheng_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '猴哥',
    value: 'zh_male_sunwukong_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '熊二',
    value: 'zh_male_xionger_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['抖音', '剪映C端', '豆包'],
    mix: true,
  },
  {
    label: '佩奇猪',
    value: 'zh_female_peiqi_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映订阅', '抖音', '豆包'],
    mix: true,
  },
  {
    label: '武则天',
    value: 'zh_female_wuzetian_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映'],
    mix: true,
  },
  {
    label: '顾姐',
    value: 'zh_female_gujie_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['抖音', '剪映C端'],
    mix: true,
  },
  {
    label: '樱桃丸子',
    value: 'zh_female_yingtaowanzi_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['剪映订阅', '抖音', '豆包'],
    mix: true,
  },
  {
    label: 'zh_male_chunhui_mars_bigtts',
    value: '中文',
    languages: ['剪映'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: 'zh_female_shaoergushi_mars_bigtts',
    value: '中文',
    languages: ['是'],
    emotions: [],
    business: ['抖音', '剪映C端', '豆包'],
    mix: true,
  },
  {
    label: '俏皮女声',
    value: 'zh_female_qiaopinvsheng_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '懒音绵宝',
    value: 'zh_male_lanxiaoyang_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '亮嗓萌仔',
    value: 'zh_male_dongmanhaimian_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '磁性解说男声/Morgan',
    value: 'zh_male_jieshuonansheng_mars_bigtts',
    languages: ['中文', '美式英语'],
    emotions: [],
    business: ['抖音', '剪映'],
    mix: true,
  },
  {
    label: '鸡汤妹妹/Hope',
    value: 'zh_female_jitangmeimei_mars_bigtts',
    languages: ['中文', '美式英语'],
    emotions: [],
    business: ['抖音', '豆包'],
    mix: true,
  },
  {
    label: '贴心女声/Candy',
    value: 'zh_female_tiexinnvsheng_mars_bigtts',
    languages: ['中文', '美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '萌丫头/Cutey',
    value: 'zh_female_mengyatou_mars_bigtts',
    languages: ['中文', '美式英语'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '内敛才俊',
    value: 'ICL_zh_male_neiliancaijun_e991be511569_tob',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '温暖少年',
    value: 'ICL_zh_male_yangyang_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: '儒雅公子',
    value: 'ICL_zh_male_flc_v1_tob',
    languages: ['中文'],
    emotions: [],
    business: ['StoryAi'],
    mix: true,
  },
  {
    label: 'zh_male_changtianyi_mars_bigtts',
    value: '中文',
    languages: ['剪映C端', '抖音', '豆包'],
    emotions: [],
    business: [],
    mix: true,
  },
  {
    label: '儒雅青年',
    value: 'zh_male_ruyaqingnian_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['番茄小说', '豆包', '剪映'],
    mix: true,
  },
  {
    label: '霸气青叔',
    value: 'zh_male_baqiqingshu_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['番茄小说', '豆包', '剪映', '剪映-Dreamina'],
    mix: true,
  },
  {
    label: '擎苍',
    value: 'zh_male_qingcang_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: ['番茄小说', '剪映', '豆包', '抖音'],
    mix: true,
  },
  {
    label: '活力小哥',
    value: 'zh_male_yangguangqingnian_mars_bigtts',
    languages: ['中文'],
    emotions: [],
    business: [],
    mix: true,
  },
]

export type EmotionValue = | 'happy'
  | 'sad'
  | 'angry'
  | 'surprised'
  | 'fear'
  | 'hate'
  | 'excited'
  | 'coldness'
  | 'neutral'
  | 'depressed'
  | 'lovey_dovey'
  | 'shy'
  | 'comfort'
  | 'tension'
  | 'tender'
  | 'storytelling'
  | 'radio'
  | 'magnetic'
  | 'advertising'
  | 'vocal_fry'
  | 'asmr'
  | 'news'
  | 'entertainment'
  | 'dialect'
  // 英文集常见分类
  | 'chat'
  | 'warm'
  | 'affectionate'
  | 'authoritative'
  // 兜底（很少用到，防止新情感/拼写导致类型错误）
  | `custom_${string}`

export interface EmotionOption {
  label: string
  value: EmotionValue
}

export interface Speaker {
  label: string
  value: string // 语音模型ID
  languages: string[] // ['中文'] / ['美式英语'] / ...
  emotions: string[] | EmotionOption[]
  business: string[] // 上线业务方
  mix: boolean // 是否支持MIX
}

// 升级后的强类型
export type UpgradedSpeaker = Omit<Speaker, 'emotions'> & {
  emotions: EmotionOption[]
}

// —— 情感映射（中文/英文/常见别名统一收敛到 EmotionValue）——
const zhEmotionMap: Record<string, EmotionValue> = {
  '开心': 'happy',
  '悲伤': 'sad',
  '生气': 'angry',
  '愤怒': 'angry',
  '惊讶': 'surprised',
  '恐惧': 'fear',
  '厌恶': 'hate',
  '激动': 'excited',
  '冷漠': 'coldness',
  '中性': 'neutral',
  '沮丧': 'depressed',
  '撒娇': 'lovey_dovey',
  '害羞': 'shy',
  '安慰鼓励': 'comfort',
  '咆哮': 'tension',
  '咆哮/焦急': 'tension',
  '焦急': 'tension',
  '温柔': 'tender',
  '讲故事': 'storytelling',
  '自然讲述': 'storytelling',
  '讲故事 / 自然讲述': 'storytelling',
  '情感电台': 'radio',
  '磁性': 'magnetic',
  '广告营销': 'advertising',
  '气泡音': 'vocal_fry',
  '低语': 'asmr',
  '低语 (ASMR)': 'asmr',
  '低语（ASMR）': 'asmr',
  'ASMR': 'asmr',
  '新闻播报': 'news',
  '娱乐八卦': 'entertainment',
  '方言': 'dialect',

  // 英文字段在中文表述时的常见翻译
  '愉悦': 'happy',
  '对话': 'chat',
  '闲聊': 'chat',
  '温暖': 'warm',
  '深情': 'affectionate',
  '权威': 'authoritative',
}

const enEmotionMap: Record<string, EmotionValue> = {
  // 英文集合（通常 UI 展示中文，这里兼容中文到英文集合值）
  '中性': 'neutral',
  '愉悦': 'happy',
  '生气': 'angry',
  '愤怒': 'angry',
  '悲伤': 'sad',
  '兴奋': 'excited',
  '对话': 'chat',
  '闲聊': 'chat',
  '低语': 'asmr',
  '低语 (ASMR)': 'asmr',
  '低语（ASMR）': 'asmr',
  'ASMR': 'asmr',
  '温暖': 'warm',
  '深情': 'affectionate',
  '权威': 'authoritative',
  // 复用中文映射，做最大兼容
  ...zhEmotionMap,
}

// —— 工具函数 ——

// 判断是否“英文系”音色（用于选择映射表）
function isEnglishSpeaker(item: Speaker): boolean {
  const langHit
    = Array.isArray(item.languages) && item.languages.some(l => /英语/.test(l))
  const idHit = item.value.startsWith('en_')
  return langHit || idHit
}

// 将任意文本安全转换为 custom key（兜底）
function toSafeCustomKey(s: string): EmotionValue {
  const base = String(s || '')
    .toLowerCase()
    .replace(/[（）()]/g, '')
    .replace(/\s+/g, '_')
    .replace(/\W+/g, '_')
    .replace(/^_+|_+$/g, '')
  return (`custom_${base || 'unknown'}`) as EmotionValue
}

// 去重（按 value 去重，保留首个 label）
function dedupeEmotions(arr: EmotionOption[]): EmotionOption[] {
  const seen = new Set<string>()
  const res: EmotionOption[] = []
  for (const e of arr) {
    if (!seen.has(e.value)) {
      seen.add(e.value)
      res.push(e)
    }
  }
  return res
}

// 把单个 speaker 的 emotions 升级成 {label,value}[]
export function normalizeSpeakerEmotions(sp: Speaker): EmotionOption[] {
  const dict = isEnglishSpeaker(sp) ? enEmotionMap : zhEmotionMap
  const raw = Array.isArray(sp.emotions) ? sp.emotions : []
  const out: EmotionOption[] = []

  for (const item of raw) {
    // 已经是 {label,value}
    if (typeof item === 'object' && item !== null && 'label' in item && 'value' in item) {
      const eo = item as EmotionOption
      // 校验 value 是否是联合类型之一，否则兜底 custom
      const safeValue = (Object.values<string>(dict).includes(eo.value) ? eo.value : toSafeCustomKey(eo.value)) as EmotionValue
      out.push({ label: eo.label, value: safeValue })
      continue
    }

    // string -> EmotionOption
    const label = String(item ?? '').trim()
    if (!label)
      continue

    const mapped = dict[label]
    const value: EmotionValue = mapped ?? toSafeCustomKey(label)
    out.push({ label, value })
  }

  return dedupeEmotions(out)
}

// 纯函数：返回“升级后的副本”，不改原数组
export function upgradeSpeakerList(list: Speaker[]): UpgradedSpeaker[] {
  return list.map(sp => ({
    ...sp,
    emotions: normalizeSpeakerEmotions(sp),
  }))
}

// 原地升级 + 类型断言：调用后在本作用域把 list 视作 UpgradedSpeaker[]
export function upgradeSpeakerListInPlace(list: Speaker[]): asserts list is UpgradedSpeaker[] {
  for (let i = 0; i < list.length; i++) {
    (list[i] as any).emotions = normalizeSpeakerEmotions(list[i])
  }
}

/* ============= 使用示例（在你的 speakerList 定义之后调用一次）=============

import { speakerList } from '@/constants/speakers'; // 你的原始大数组（emotions 还是 string[]）
import { upgradeSpeakerListInPlace } from '@/utils/upgradeSpeakers';

// 原地升级（推荐）
upgradeSpeakerListInPlace(speakerList);

// 现在 speakerList 的类型在本文件里就能当作 UpgradedSpeaker[] 使用：
// speakerList[0].emotions: EmotionOption[] -> {label,value}

================================================================== */
